version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    volumes:
      - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "8080:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5
    networks:
      - blogging_app_network
  
networks:
  blogging_app_network:
    external: true