version: '3.8'

services:    
  user_app:
    container_name: user_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./:/app
    depends_on:
      - users_db
    links:
      - users_db
    networks:
      - blogging_app_network

    
  users_db:
    image: postgres:15
    container_name: users_db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - ~/app/postgres:/var/lib/postgresql@15/data
    networks:
      - blogging_app_network

networks:
  blogging_app_network:
    external: true
