version: '3.8'

services:
  api_gateway:
    container_name: api_gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - blogging_app_network

networks:
  blogging_app_network:
    external: true
    

