version: '3.9'

services:
  fastapi:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - blogging_app_network
    volumes:
      - ./app:/app
 
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    networks:
      - blogging_app_network
    volumes:
      - ~/app/postgres:/var/lib/postgresql/data

networks:
  blogging_app_network:
    external: true