version: '3.8'

services:
  blog_app:
    container_name: blog_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - blogs_db
    links:
      - blogs_db
    networks:
      - blogging_app_network

  blogs_db:
    image: postgres:13
    container_name: blogs_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogs
    networks:
      - blogging_app_network
    volumes:
      - ~/app/postgres:/var/lib/postgresql/data

networks:
  blogging_app_network:
    external: true
