version: '3.9'

services:
  comments_app:
    container_name: comments_app
    build: .
    ports:
      - "8005:8005"
    env_file:
      - .env
    depends_on:
      - comment_db
    networks:
      - blogging_app_network
    volumes:
      - ./app:/app
 
  comment_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    networks:
      - blogging_app_network
    volumes:
      - ~/app/postgres:/var/lib/postgresql@15/data

networks:
  blogging_app_network:
    external: true